version: 0.2

phases:
  build:
    commands:
      - echo "Packaging application"
      - chmod +x app/scripts/*.sh

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  base-directory: app
  files:
    - "**/*"
